#!/bin/bash
################################################################################
# SPRINT 62 - Script 5: Atualização das Configurações da Aplicação
# 
# Este script atualiza os arquivos de configuração com as novas credenciais
# 
# EXECUTAR NO VPS como root via SSH
#
# Autor: GenSpark AI
# Data: 2025-11-16
################################################################################

set -e  # Exit on error

echo "=========================================================================="
echo "  SPRINT 62 - Atualização de Configurações"
echo "=========================================================================="
echo ""

# Verificar se está rodando como root
if [ "$EUID" -ne 0 ]; then 
    echo "❌ ERRO: Este script deve ser executado como root"
    echo "   Use: sudo bash 5_update_config.sh"
    exit 1
fi

# Configurações
SITE_NAME="prestadores"
SITE_ROOT="/opt/webserver/sites/$SITE_NAME/public_html"
CONFIG_FILE="$SITE_ROOT/config/database.php"

echo "📋 Configuração:"
echo "   Site Root: $SITE_ROOT"
echo "   Config File: $CONFIG_FILE"
echo ""

# Verificar se o diretório existe
if [ ! -d "$SITE_ROOT" ]; then
    echo "❌ ERRO: Diretório do site não encontrado: $SITE_ROOT"
    exit 1
fi

# Solicitar credenciais do banco de dados
echo "🔐 Digite as credenciais do banco de dados do VPS"
echo "   (As mesmas usadas no Script 4)"
echo ""
read -p "   Database Name [$SITE_NAME_db]: " DB_NAME
DB_NAME=${DB_NAME:-"${SITE_NAME}_db"}

read -p "   Database User [${SITE_NAME}_user]: " DB_USER
DB_USER=${DB_USER:-"${SITE_NAME}_user"}

read -s -p "   Database Password: " DB_PASS
echo ""

read -p "   Database Host [localhost]: " DB_HOST
DB_HOST=${DB_HOST:-"localhost"}

echo ""

if [ -z "$DB_PASS" ]; then
    echo "❌ ERRO: Senha não pode ser vazia"
    exit 1
fi

# Testar conexão
echo "🚀 Etapa 1: Testando conexão com o banco de dados..."
mysql -u "$DB_USER" -p"$DB_PASS" -h "$DB_HOST" "$DB_NAME" -e "SELECT 1;" &> /dev/null

if [ $? -ne 0 ]; then
    echo "❌ ERRO: Não foi possível conectar ao banco de dados"
    echo "   Verifique as credenciais e tente novamente"
    exit 1
fi

echo "✅ Conexão estabelecida!"
echo ""

# Fazer backup do config atual
echo "🚀 Etapa 2: Fazendo backup das configurações atuais..."
if [ -f "$CONFIG_FILE" ]; then
    BACKUP_FILE="${CONFIG_FILE}.backup_$(date +%Y%m%d_%H%M%S)"
    cp "$CONFIG_FILE" "$BACKUP_FILE"
    echo "   ✅ Backup salvo: $BACKUP_FILE"
else
    echo "   ⚠️  Arquivo de configuração não encontrado, será criado"
fi
echo ""

# Criar novo arquivo de configuração
echo "🚀 Etapa 3: Criando novo arquivo de configuração..."

mkdir -p "$(dirname "$CONFIG_FILE")"

cat > "$CONFIG_FILE" << EOF
<?php
/**
 * Configuração do Banco de Dados
 * 
 * Atualizado automaticamente pela migração VPS
 * Data: $(date '+%Y-%m-%d %H:%M:%S')
 */

return [
    'host' => '$DB_HOST',
    'database' => '$DB_NAME',
    'username' => '$DB_USER',
    'password' => '$DB_PASS',
    'charset' => 'utf8mb4',
    'collation' => 'utf8mb4_unicode_ci',
    'prefix' => '',
];
EOF

echo "   ✅ Arquivo criado"
echo ""

# Ajustar permissões
echo "🚀 Etapa 4: Ajustando permissões..."
chown $SITE_NAME:$SITE_NAME "$CONFIG_FILE"
chmod 640 "$CONFIG_FILE"  # Somente owner pode ler/escrever
echo "   ✅ Permissões: 640 (rw-r-----)"
echo ""

# Atualizar outros arquivos de configuração se necessário
echo "🚀 Etapa 5: Verificando outros arquivos de configuração..."

# config/app.php
APP_CONFIG="$SITE_ROOT/config/app.php"
if [ -f "$APP_CONFIG" ]; then
    echo "   📄 Encontrado: config/app.php"
    
    # Fazer backup
    cp "$APP_CONFIG" "${APP_CONFIG}.backup_$(date +%Y%m%d_%H%M%S)"
    
    # Atualizar URL base (se necessário)
    # sed -i "s|'base_url' => '.*'|'base_url' => 'https://prestadores.clinfec.com.br'|g" "$APP_CONFIG"
    
    echo "   ℹ️  Revise manualmente se necessário"
fi

# config/config.php
GENERAL_CONFIG="$SITE_ROOT/config/config.php"
if [ -f "$GENERAL_CONFIG" ]; then
    echo "   📄 Encontrado: config/config.php"
    cp "$GENERAL_CONFIG" "${GENERAL_CONFIG}.backup_$(date +%Y%m%d_%H%M%S)"
    echo "   ℹ️  Revise manualmente se necessário"
fi

echo ""

# Criar arquivo .env se não existir
ENV_FILE="$SITE_ROOT/.env"
if [ ! -f "$ENV_FILE" ]; then
    echo "🚀 Etapa 6: Criando arquivo .env..."
    cat > "$ENV_FILE" << EOF
# Environment Configuration
# Generated by migration script
# Date: $(date '+%Y-%m-%d %H:%M:%S')

APP_ENV=production
APP_DEBUG=false
APP_URL=https://prestadores.clinfec.com.br

DB_HOST=$DB_HOST
DB_DATABASE=$DB_NAME
DB_USERNAME=$DB_USER
DB_PASSWORD=$DB_PASS

# Timezone
APP_TIMEZONE=America/Sao_Paulo
EOF

    chown $SITE_NAME:$SITE_NAME "$ENV_FILE"
    chmod 640 "$ENV_FILE"
    echo "   ✅ Arquivo .env criado"
else
    echo "   ℹ️  Arquivo .env já existe, não modificado"
fi

echo ""
echo "🚀 Etapa 7: Criando arquivo de informações da migração..."
INFO_FILE="$SITE_ROOT/MIGRATION_INFO.txt"
cat > "$INFO_FILE" << EOF
========================================================================
  INFORMAÇÕES DA MIGRAÇÃO - VPS
========================================================================

Data da Migração: $(date '+%Y-%m-%d %H:%M:%S')
Script: Sprint 62 - Migração Hostinger → VPS

BANCO DE DADOS:
  Host: $DB_HOST
  Database: $DB_NAME
  User: $DB_USER
  (Senha: armazenada em config/database.php)

DIRETÓRIOS:
  Root: $SITE_ROOT
  Public: $SITE_ROOT/public
  Config: $SITE_ROOT/config
  Logs: $SITE_ROOT/logs

SERVIDOR:
  IP: $(hostname -I | awk '{print $1}')
  Hostname: $(hostname)
  SO: $(cat /etc/os-release | grep PRETTY_NAME | cut -d'"' -f2)
  PHP: $(php -v | head -1)
  NGINX: $(nginx -v 2>&1)

PRÓXIMOS PASSOS:
  1. Configurar DNS para apontar prestadores.clinfec.com.br para este IP
  2. Gerar certificado SSL (Script 6)
  3. Testar aplicação
  4. Validar todas as funcionalidades

========================================================================
EOF

chmod 644 "$INFO_FILE"
echo "   ✅ Arquivo criado: $INFO_FILE"

echo ""
echo "=========================================================================="
echo "  ✅ SCRIPT 5 CONCLUÍDO"
echo "=========================================================================="
echo ""
echo "📊 Resumo:"
echo "   ✅ Configuração do banco atualizada"
echo "   ✅ Permissões ajustadas"
echo "   ✅ Arquivo .env criado"
echo "   ✅ Informações da migração documentadas"
echo ""
echo "📤 Próximos passos:"
echo "   1. Configure o DNS (veja instruções no Script 6)"
echo "   2. Gere o certificado SSL"
echo "   3. Teste a aplicação"
echo ""
echo "🌐 Acesso temporário via IP:"
echo "   http://$(hostname -I | awk '{print $1}')"
echo ""
